[21228] Improve CI workflows for different repos
eProsima/eProsima-CI pull request #110
Opened 2024-06-26 15:04 UTC by JesusPoderoso

## Description
This PR introduces several improvements regarding CI procedures in different eProsima repositories.
Related PRs: 
- https://github.com/eProsima/Fast-DDS-python/pull/149 (and related backports)

List of changes that this PR introduces:
- External (multiplatform) action to install doxygen (windows oriented)
- Multiplatform action to obtain related branch from the given repository (calls existing ubuntu action)
- Windows action to merge different  .meta files into a single file 

## Contributor Checklist
- [x] Commit messages follow the company guidelines. 
- [x] Changes are API compatible. 
- [ ] New features have been added to the `versions.md` and `README.md` files (if applicable).

## Reviewer Checklist
- [ ] The title and description correctly express the PR's purpose.
- [ ] The Contributor checklist is correctly filled.

2024-06-27 13:34 UTC, EduPonz requested changes

2024-06-27 13:34 UTC, EduPonz commented on windows/merge_yaml_metas/action.yml
> +        $combined_content | Out-File -FilePath ${{ inputs.path }} -Encoding UTF8
I suggest printing out the meta file at the end

2024-06-27 13:46 UTC, JesusPoderoso commented on windows/merge_yaml_metas/action.yml
> +        $combined_content | Out-File -FilePath ${{ inputs.path }} -Encoding UTF8
Check [this workflow run](https://github.com/eProsima/Fast-DDS-python/actions/runs/9697667048?pr=149)

2024-06-28 07:01 UTC, EduPonz approved these changes

2024-06-28 07:01 UTC, merged