Feature/ubuntu 24
eProsima/eProsima-CI pull request #112
Opened 2024-07-08 08:13 UTC by rsanchez15

## Description

## Contributor Checklist
- [ ] Commit messages follow the company guidelines. 
- [ ] Changes are API compatible. 
- [ ] New features have been added to the `versions.md` and `README.md` files (if applicable).

## Reviewer Checklist
- [ ] The title and description correctly express the PR's purpose.
- [ ] The Contributor checklist is correctly filled.

2024-07-11 14:54 UTC, irenebm requested changes
Please, update the [README.md](https://github.com/eProsima/eProsima-CI/blob/feature/ubuntu-24/README.md#artifacts-uploaded) with the new artifact names and remove the outdated ones.

2024-07-11 14:54 UTC, irenebm commented on .github/workflows/configurations/metas/ubuntu-24.04/colcon.meta
> +{
Is it necessary to keep the `ubuntu-20.04/colcon.meta` file?

2024-07-11 14:54 UTC, irenebm commented on .github/workflows/build_dev_utils.yml
> +      - name: Setup Python Virtual Environment
Could you consider adding a TODO note for implementing a similar Python virtual environment setup for Windows in the future or explaining that this setup is required for Ubuntu 24.04, and we've included it for Ubuntu 22.04 as well for consistency?

2024-07-12 07:24 UTC, rsanchez15 commented on .github/workflows/configurations/metas/ubuntu-24.04/colcon.meta
> +{
Not really. Removed

2024-07-12 07:29 UTC, irenebm approved these changes
LGTM

2024-07-15 09:46 UTC, irenebm approved these changes
LGTM

2024-07-15 09:55 UTC, EduPonz requested changes

2024-07-15 09:55 UTC, EduPonz commented on ubuntu/install_python_packages/action.yml
> +        python -m pip install --upgrade setuptools
```suggestion
        python3 -m ensurepip --upgrade
        python3 -m pip3 install --upgrade setuptools
```

2024-07-15 13:04 UTC, rsanchez15 commented on ubuntu/install_python_packages/action.yml
> +        python -m pip install --upgrade setuptools
Tested in Fast DDS CI

2024-07-15 13:26 UTC, EduPonz requested changes

2024-07-15 13:26 UTC, EduPonz commented on versions.md
> +- Remove nightly builds for Ubuntu 22.04.
```suggestion
- Remove nightly builds for Ubuntu 20.04.
```

2024-07-15 13:26 UTC, EduPonz commented on versions.md
> +- Extended the action for installing python packages to setup a virtual environment.
Missing the item for the new Ubuntu `setup_python_venv` action

2024-07-15 13:29 UTC, EduPonz approved these changes

2024-07-15 13:30 UTC, merged