Rebase fork over upstream repo
eProsima/eProsima-CI pull request #17
Opened 2023-04-20 06:35 UTC by jparisu

2023-04-20 12:58 UTC, JLBuenoLopez-eProsima reviewed
Partial review.

2023-04-20 12:58 UTC, JLBuenoLopez-eProsima commented on multiplatform/colcon_build/action.yml
> +        # TODO find a way to use it for windows
Maybe a comment explaining the issue in Windows might be helpful.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima reviewed
Second partial review. Only a few more files to review.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on ubuntu/colcon_build/action.yml
> +        echo "::group::Compile colcon ${{ inputs.workspace }}"
```suggestion
        echo "::group::Compile using colcon ${{ inputs.workspace }}"
```

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on windows/colcon_build/action.yml
> +            -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} ${{ inputs.cmake_args_default }} ${{ inputs.cmake_args }}
I suppose that passing any non empty `inputs.cmake_args_default` causes a failure (seeing the comments above).

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on windows/colcon_build/action.yml
> +          -StartInPath (pwd) -DevCmdArguments '/arch=x64 /host_arch=x64'
Not completely sure what this does :sweat_smile:

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on windows/colcon_build/action.yml
> +        }
Here the `colcon.meta` should be removed if it has been created. Not checked again and reset the environment variable.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/asan_build_test/action.yml
> +    default: '-DBUILD_TESTS=ON -DASAN_BUILD=ON -DCMAKE_BUILD_TYPE=Debug'
Should not these flags be enforced directly so the user cannot inadvertently disable them?

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/clang_build_test/action.yml
> +description: 'Compile code with colcon and using ASAN flags, and run colcon test.'
This comment should be updated to indicate the goal of this specific action.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/clang_build_test/action.yml
> +    description: 'flags to colcon build execution'
```suggestion
    description: 'flags to pass to colcon build execution'
```

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/clang_tidy_check/action.yml
> +    description: 'Directory where builds are'
```suggestion
    description: 'Binaries directory'
```

What do you think? If accepted, please apply to the platform actions as well.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on ubuntu/clang_tidy_check/action.yml
> +      # when this is not the expected behavior (it actually remove set -e)
I do not understand what you are trying to clarify with the information inside the parentheses.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on windows/clang_tidy_check/action.yml
> +      shell: bash
Should not it be powershell? Though I am seeing that it is unsupported. Maybe we should not include this action and throw directly the error in the multiplatform action.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/colcon_build_test_flaky/action.yml
> +    default: '--label-regex "xfail"'
I think this should be enforced in the action instead of leaving the ability to override it.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/colcon_test/action.yml
> +description: 'Import some repositories and their versions from a yaml file'
Update description. Apply to related platform actions too.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/colcon_test/action.yml
> +    description: 'Workspace where built is done'
```suggestion
    description: 'Current workspace'
```

Please, apply also to related platform actions.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on windows/colcon_test/action.yml
> +            ${{ inputs.ctest_args_default }} ${{ inputs.ctest_args }}
So this works but not in case of `--cmake-args` for `colcon build`. That is weird!

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/download_dependency/action.yml
> +    description: 'Secret token to authenticate the WebRequest so it not get a rate limit error.'
```suggestion
    description: 'Secret token to authenticate the WebRequest so it does not get a rate limit error.'
```

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/download_dependency/action.yml
> +      uses: dawidd6/action-download-artifact@v2
I think that every other external action used was taken from the `actions` repository. Using this external action, we should check license compatibility (it is MIT license) and assess the risk of the external dependency.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/get_workflow_id/action.yml
> +# TODO this action takes only into consideration the last complete job, and not the look deeper if the name does not match.
```suggestion
# TODO this action takes only into consideration the last complete job, and it does not look deeper if the name does not match.
```

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/get_workflow_id/action.yml
> +# TODO this action takes only into consideration the last complete job, and not the look deeper if the name does not match.
I think this action has been superseded by the use of  `dawidd6/action-download-artifact@v2`. Am I correct? I think this action is not being used by no workflow and that its intention is just related with the `download_dependency` action. If so, I think we can remove it and its child actions from the PR.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on windows/get_workflow_id/action.yml
> +# TODO this action takes only into consideration the last complete job, and not the look deeper if the name does not match.
Not reviewed as it is possible that it is not needed. If confirm to be correct, I will review it.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on ubuntu/get_workflow_id/action.yml
> +name: 'get_workflow_id'
Not reviewed as it is possible that it is not needed. If confirm to be correct, I will review it.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on ubuntu/get_workflow_id/action.yml
> +  # This action is not used anymore as dawidd6/action-download-artifact already look for the workflow id
My suspicions are confirmed. Then, my suggestion is to remove these actions from the PR.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on windows/install_yamlcpp/action.yml
> +name: install_yamlcpp
Not reviewed as Elbrus team does not use this dependency and I am not used to its requirements.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/tsan_build_test/action.yml
> +    default: '-DBUILD_TESTS=ON -DTSAN_BUILD=ON -DCMAKE_BUILD_TYPE=Debug'
Again, I think these arguments should be enforced instead of being possible to override them.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on multiplatform/tsan_build_test/action.yml
> +    - name: Build
```suggestion
    - name: Build and test
```

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on ubuntu-22.04/uncrustify/action.yml
>          path: src
Changes in this file should be reverted.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on ubuntu/coverage_build_test_upload/action.yml
> +    description: 'path to codecov yml fixes file'
I am not sure about what the use of this variable.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on ubuntu/coverage_build_test_upload/action.yml
> +    default: '-DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug'
Enforce these options instead leaving the ability to the user of overriding them.

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on ubuntu/coverage_build_test_upload/action.yml
> +    description: 'flags to colcon test execution'
```suggestion
    description: 'flags passed to colcon test execution'
```

2023-04-20 13:47 UTC, JLBuenoLopez-eProsima commented on ubuntu/coverage_build_test_upload/action.yml
> +name: 'coverage_build_test_upload'
Actions that are prepared and run in a single platform should be clearly documented in the README.

2023-04-21 10:22 UTC, jparisu commented on README.md
> +## Steps Implemented
I'll leave this to a future commit with documentation changes. Do not resolve conversation

2023-04-21 10:32 UTC, jparisu commented on README.md
> +## Full Actions Implemented
Finally I did it in a way that could be run from ubuntu 20 and 22.
I think it is better than having it in `ubuntu` folder and not be able to run it from one of them.

2023-04-21 10:35 UTC, jparisu commented on .github/workflows/build_fastdds.yml
> +        description: 'Addition to artifacts name creation (use non default postfix when creating artifacts with specific arguments).'
mm... no, is not. It is a suggestion saying that if you want to execute manually, use a non-default value.
What I meant was that people should be careful about launching this manually because it can affect other workflows, and thus each value should be different (from default and from other values)

2023-04-21 10:38 UTC, jparisu commented on .github/workflows/build_fastdds.yml
> +      - name: Sync this repository
I do not think saying this is ambiguous, and it helps when copying and pasting (that is a lot).

2023-04-21 10:39 UTC, jparisu commented on .github/workflows/build_fastdds.yml
> +        uses: jparisu/eProsima-CI/multiplatform/get_configurations_from_repo@main
I would update so as the last commit before merging. If I do so before that, there is no way to test these actions

2023-04-21 10:40 UTC, jparisu commented on .github/workflows/configurations/fastdds/dependencies.repos
> +    fastrtps:
_But what is the proper name?_ :new_moon_with_face:

2023-04-21 10:58 UTC, jparisu commented on .github/workflows/build_fastdds.yml
> +        uses: jparisu/eProsima-CI/multiplatform/generate_dependency@main
That is not what the action does. It generates an artifact (so I would change it to `generate_artifact`) but it does not generate only Fast DDS, it is used for any other artifact that is built with colcon (that is why I suggested generate_dependency to be clear that is not any artifact, only library dependencies)

2023-04-21 11:00 UTC, jparisu commented on multiplatform/generate_dependency/action.yml
> +    description: '.repos file to import repositories'
This is not correct, they are dowloaded in ./src

2023-04-21 11:01 UTC, jparisu commented on multiplatform/generate_dependency/action.yml
> +      uses: jparisu/eProsima-CI/multiplatform/install_fast_dependencies@main
I removed this step in action

2023-04-21 11:04 UTC, jparisu commented on ubuntu/install_fast_dependencies/action.yml
> +    required: false
We can discuss this further and arrive to a consensus. I would prefer to keep symmetry.

2023-04-21 11:06 UTC, jparisu commented on ubuntu/get_file_from_repo/action.yml
> +        echo "Calling wget with url: https://raw.githubusercontent.com/${{ inputs.source_repository }}/${{ inputs.source_repository_branch }}/${{ inputs.file_name }}"
good catch

2023-04-21 11:07 UTC, jparisu commented on ubuntu/install_fast_dependencies/action.yml
> +      uses: jparisu/eProsima-CI/ubuntu/install_python_packages@main
It was because install_python had custom packages before

2023-04-21 11:15 UTC, jparisu commented on ubuntu/install_gtest/action.yml
> +    - name: install_apt_packages
This was a copy paste

2023-04-21 11:37 UTC, jparisu commented on windows/install_colcon/action.yml
> +        pip3 install vcstool
1. It is installed now
2. Yes and no. It could indeed be a `install_python_packages` in windows. What it cannot be done is a `multiplatform/install_python_packages` action. Because we cannot assume that different apps and tools are installed using the same methods in ubuntu and windows. It may be the case, but I would not assume so (as we cannot assume choco is symmetrical to apt)

2023-04-21 11:47 UTC, jparisu commented on ubuntu/vcs_import/action.yml
> +description: 'Import some repositories and their versions from a yaml file'
.repos is a yaml file :thinking:

2023-04-21 11:56 UTC, jparisu commented on multiplatform/colcon_build/action.yml
> +    default: '--event-handlers=console_direct+'
I thought the same. I made it this way to be symmetric with `cmake_args_default` and because I wanted to do it as generic as possible. But we can remove it. To public opinion list.

2023-04-21 12:00 UTC, jparisu commented on multiplatform/colcon_build/action.yml
> +        # TODO find a way to use it for windows
It is not an issue, is just that flags are different.
This is tricky because we want to use a "default" argument that is defaulted differently in two places... How good it brings the python `None` xD

2023-04-21 12:12 UTC, jparisu commented on ubuntu/install_gcov/action.yml
> +        custom_packages: gcovr==5.0
This is how we had it in other repos, but I have not done the test of using only one... I add a tag to do it in other moment

2023-04-21 12:14 UTC, jparisu commented on ubuntu/get_platform/action.yml
> +name: 'fgt_platform'
Actually I used it in first revision

2023-04-21 12:18 UTC, jparisu commented on ubuntu/install_documentation_requirements/action.yml
> +          sphinx-tabs==3.2.0
I agree with first suggestion, but I do not know where to put it... It must be somewhere in eProsima-CI, but then it is more difficult to use this action.
About the second one, I would try to unify a bit, so maybe having it in cpp-style along with other configurations, or even here seems better to me

2023-04-21 12:19 UTC, jparisu commented on ubuntu/install_documentation_requirements/action.yml
> +          sphinx-tabs==3.2.0
Actually, I am thinking that may be a good idea to have a folder with configurations and have also uncrustify and python linter ones...

2023-04-21 12:21 UTC, jparisu commented on ubuntu/sphinx_docs/action.yml
> +    default: '-DBUILD_DOCS=ON -DBUILD_DOCS_TESTS=ON'
These arguments are widely used in our repos, and also in `cmake_utils` (future cmake central point of eProsima :new_moon_with_face: ) so I would leave it this way and change it just in repos that do not follow this (that is only Fast DDS docs I think)

2023-04-21 12:22 UTC, jparisu commented on ubuntu/sphinx_docs/action.yml
> +        target_workspace: '${{ github.workspace }}/install'
I would rather modify other repos to follow our model :new_moon_with_face: 
Now being serious, I would not remove this. If so, changing the name to `annapurna_sphinx_docs`.

2023-04-24 05:51 UTC, jparisu commented on windows/colcon_build/action.yml
> +            -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} ${{ inputs.cmake_args_default }} ${{ inputs.cmake_args }}
I do not get why and I do not know which comments do you refer to. It does not fail with empty arg, at least I do not see why.

2023-04-24 05:53 UTC, jparisu commented on windows/colcon_build/action.yml
> +          -StartInPath (pwd) -DevCmdArguments '/arch=x64 /host_arch=x64'
Overall, this command searches for the first instance of the Microsoft.VisualStudio.DevShell.dll file in the Visual Studio installation directories, imports the associated PowerShell module, and launches the Visual Studio development shell with the specified options.
Barro's work

2023-04-24 06:24 UTC, jparisu commented on windows/colcon_test/action.yml
> +            ${{ inputs.ctest_args_default }} ${{ inputs.ctest_args }}
Colcon allow an empty `--cmake-args` and `--ctest-args`.
The problem here is that in pwsh having an empty string after a ` fails. Thus, all possible blank arguments that goes at the end of the command must be in the same line

2023-04-24 06:27 UTC, jparisu commented on multiplatform/download_dependency/action.yml
> +      uses: dawidd6/action-download-artifact@v2
It is MIT license: https://github.com/dawidd6/action-download-artifact/blob/master/LICENSE

2023-04-24 06:30 UTC, jparisu commented on multiplatform/get_workflow_id/action.yml
> +# TODO this action takes only into consideration the last complete job, and not the look deeper if the name does not match.
I do not agree in removing any action that is not currently used. The action is fine and can be useful in the future.

2023-04-24 06:32 UTC, jparisu commented on windows/install_yamlcpp/action.yml
> +name: install_yamlcpp
@rsanchez15

2023-04-24 06:35 UTC, jparisu commented on ubuntu-22.04/uncrustify/action.yml
>          path: src
review it again, changes were made

2023-04-24 06:37 UTC, jparisu commented on ubuntu/coverage_build_test_upload/action.yml
> +name: 'coverage_build_test_upload'
Left to future documentation commit

2023-04-24 09:11 UTC, rsanchez15 commented on .github/workflows/build_dev_utils.yml
> +    - cron: '0 1 * * *'
I'm not sure if "build_fastdds" can be completed in an hour. I'll leave two hours between each dependent build (dev-utils at 2 AM and ddspipe at 4AM)

2023-04-24 09:15 UTC, rsanchez15 commented on .github/workflows/build_fastdds.yml
> +        uses: jparisu/eProsima-CI/multiplatform/generate_dependency@main
I'd keep `build_fastdds` and explain all this in the upper comments

2023-04-24 10:41 UTC, jparisu commented on .github/workflows/build_dev_utils.yml
> +    - cron: '0 1 * * *'
It finished before, because there are no tests. However I changed them so they wait to each other

2023-04-26 09:21 UTC, JLBuenoLopez-eProsima commented on README.md
> +  - [Index](#index)
I do not think these two should be in the index. Usually the table of contents does not include the title nor the table of contents itself.

2023-04-26 09:21 UTC, JLBuenoLopez-eProsima commented on README.md
> +In order to use this repository, we recommend you:
Please, avoid the personal style. Apply this suggestion to other parts in this README.

```suggestion
In order to use this repository, the following recommendations are suggested:
```

2023-04-26 09:21 UTC, JLBuenoLopez-eProsima commented on README.md
> +1. **Always use a fix version**. When using any of these actions, set it with a `@v<X>` version.
Please, break line after each sentence.

Following this recommendation, I suppose that a release policy should be stated here on the README.

2023-04-26 09:21 UTC, JLBuenoLopez-eProsima commented on README.md
> +  - Get the files that differ from one github reference to another. Can grep result.
```suggestion
  - Get the files that differ from one github reference to another. The result can be parsed with `grep`.
```

2023-04-26 09:21 UTC, JLBuenoLopez-eProsima commented on README.md
> +So far, there are 3 workflows running to upload artifacts:
```suggestion
So far, the following workflows are running to upload artifacts:
```

Instead of having to change the number each time a new workflow is added, the developer only has to add the workflow to the list.

2023-04-26 09:21 UTC, JLBuenoLopez-eProsima commented on README.md
> +These are the artifacts that are generated every night with the latest versions of each project:
Maybe a reference or explanation about which configurations options are enabled and also how to introduce some other artifact with other configuration parameters would be nice to have.

2023-04-26 09:21 UTC, JLBuenoLopez-eProsima commented on README.md
> +  uses: jparisu/eProsima-CI/multiplatform/download_dependency@main
Maybe insted of referring to `main`, this should say `vX.Y`. Even if it is not possible to directly copy the snippet, the user would have to set the proper version. Otherwise it could be overlooked.

2023-04-26 09:21 UTC, JLBuenoLopez-eProsima commented on README.md
> +In order to do so there are 2 possibilities:
I see that there is still some documentation pending

2023-04-26 09:21 UTC, JLBuenoLopez-eProsima commented on README.md
> +## Full Actions Implemented
Maybe, in order to not pollute the root directory, I suggest moving the `install_uncrustify` actions inside the `ubuntu` folder. Something like the structure shown in the following tree:

```
ubuntu
|
|- ubuntu-20.04
|   |- install_uncrustify
|
|- ubuntu-22.04
|   |- install_uncrustify
```

2023-04-26 09:38 UTC, JLBuenoLopez-eProsima reviewed
Github is messing with me. I suppose it is cause by the great number of changes. Right now it says that I have 2 reviews started and one of them I do not know how to publish the suggestions. So I am going to proceed step by step.

This suggestions apply to the `.dev` folder. Maybe the README should redirect the user for more information to these documents in the specific sections.

2023-04-26 09:38 UTC, JLBuenoLopez-eProsima commented on .dev/contributions_guidelines.md
> +4. **After revisions and correction are finished** change every version to `@main` again.
```suggestion
4. **After reviews and correction are finished** change every version to `@main` again.
```

2023-04-26 09:38 UTC, JLBuenoLopez-eProsima commented on .dev/multiplatform_support.md
> +```plantuml
Github is not formatting the UML graphs. This is intended to be read in the repository so I think we should find a manner to properly show these graphs. `mermaid` has been used in the Fast DDS QoS Profiles Manager README successfully.

2023-04-26 09:38 UTC, JLBuenoLopez-eProsima commented on .dev/multiplatform_support.md
> +Thus: `multiplatform` actions should always follow one and only one of these designs:
```suggestion
Thus, `multiplatform` actions should always follow one and only one of these designs:
```

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on ubuntu/install_fast_dependencies/action.yml
> +    required: false
I will discuss it with Elbrus team then.

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on windows/install_colcon/action.yml
> +        pip3 install vcstool
My suggestion was to have the `install_python_packages` action also available in Windows platforms to keep symmetry when possible. I understand that the same `multiplatform` action is not applicable directly.

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on multiplatform/colcon_build/action.yml
> +    default: '--event-handlers=console_direct+'
Then leave it for now and we can remove later on if we see that it is not being used.

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on multiplatform/colcon_build/action.yml
> +        # TODO find a way to use it for windows
Well, I suppose the current comment could be enough, though maybe your name can be added to the TODO in case some developer tries to fix it in the future, and have doubts.

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on windows/colcon_build/action.yml
> +            -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} ${{ inputs.cmake_args_default }} ${{ inputs.cmake_args }}
This is referring to the `TODO` comment in the multiplatform action: https://github.com/eProsima/eProsima-CI/pull/17#discussion_r1173685938

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on multiplatform/asan_build_test/action.yml
> +    default: '-DBUILD_TESTS=ON -DASAN_BUILD=ON -DCMAKE_BUILD_TYPE=Debug'
I suppose we should start agreeing on the name of the CMake options so they are used in every eProsima project. I suppose that if any other project wants to use this action it should pass the corresponding CMake options. The warning stating that `ASAN_BUILD` is not used in the project might appear in the log output, but I do not think that is something to worry about.

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on multiplatform/clang_build_test/action.yml
> +description: 'Compile code with colcon and using ASAN flags, and run colcon test.'
This suggestion have been overlooked

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on multiplatform/colcon_test/action.yml
> +    description: 'Workspace where built is done'
Then I suggest 
```suggestion
    description: 'Workspace where build has been done.
```

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on multiplatform/download_dependency/action.yml
> +      uses: dawidd6/action-download-artifact@v2
Maybe an encapsulation is not needed. But I would suggest documenting its use in README or another .dev file to keep track of external actions in use. I am worried by actions not maintained directly by Github.

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on multiplatform/get_workflow_id/action.yml
> +    description: Secret token to authenticate the WebRequest so it not get a rate limit error
```suggestion
    description: Secret token to authenticate the WebRequest so it does not get a rate limit error
```

This suggestion applies to some other places.

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on ubuntu/coverage_build_test_upload/action.yml
> +name: 'coverage_build_test_upload'
This action has not been included in the README

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on ubuntu/get_git_diff_files/action.yml
>          echo "${{ inputs.result_env_var }}=$(git diff --name-only ${{ inputs.base_ref }} ${{ inputs.head_ref }} | grep ${{ inputs.grep_args }} | tr '\n' ' ')" >> $GITHUB_ENV
This suggestion has been overlooked

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on ubuntu/install_coverage_requirements/action.yml
> +name: 'install_coverage_requirements'
This suggestion has been overlooked.

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on ubuntu/install_documentation_requirements/action.yml
> +          sphinx-tabs==3.2.0
Sounds good. And I am not against keeping them here. But being able to pass to the action a requirements file would be nice. The current action allows it (and in fact I have used it just recently for setting up the documentation CI job for the Fast DDS QoS Profiles Manager).

2023-04-26 10:59 UTC, JLBuenoLopez-eProsima commented on ubuntu/sphinx_docs/action.yml
> +        target_workspace: '${{ github.workspace }}/install'
I will discuss it with Elbrus team.

2023-04-26 11:21 UTC, JLBuenoLopez-eProsima commented on .github/workflows/build_ddspipe.yml
> +# This is used by other workflows in this and other repositories to avoid compiling dependencies every time are needed.
```suggestion
# This is used by other workflows in this and other repositories to avoid compiling dependencies every time they are needed.
```

2023-04-26 11:21 UTC, JLBuenoLopez-eProsima commented on .github/workflows/build_ddspipe.yml
> +#  Running this workflow manually there are 2 arguments to set:
Please, apply also suggestions done in fastdds workflow documentation.

2023-04-26 13:38 UTC, jparisu commented on README.md
> +## Full Actions Implemented
I am not sure if I like that; ubuntu-20 and ubuntu-22 would be a bit lost between all actions...
At least I remove `ubuntu`-20.04 from the name, so folders are 20.04 and 22.04 and are more distinguishable

2023-04-26 13:41 UTC, jparisu commented on .github/workflows/build_fastdds.yml
> +        uses: jparisu/eProsima-CI/multiplatform/generate_dependency@main
Finally I do not know what should I do.
There are many suggestions here:
1. change action name. `generate_dependency_artifact` seems correct to me.
2. name of the action that builds fast_dds

Take into account that I uploaded a new workflow that can be run manually and can generate any artifact with a .repos and a colcon.meta called `manual_build`.

2023-04-26 13:52 UTC, jparisu commented on windows/colcon_build/action.yml
> +            -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} ${{ inputs.cmake_args_default }} ${{ inputs.cmake_args }}
So the answer is no, it does not fail if inputs.cmake_args_default  is empty.

2023-04-26 14:02 UTC, jparisu commented on ubuntu/install_documentation_requirements/action.yml
> +          sphinx-tabs==3.2.0
I leave it as a TODO for the future, so we can discuss where to put the file.
Also changing it to use a file is a bit complicated because it then have to download it from somewhere and use it, and as it is not mandatory right now I'd do it later.

2023-04-26 14:28 UTC, jparisu commented on README.md
> +  - [Index](#index)
The index is autogenerated with an extension of vscode, so every time I save the file it autogenerates all. The extension allows to remove ##index but not the main one. Is it too much trouble to leave it this way?

2023-04-26 14:47 UTC, jparisu commented on README.md
> +  uses: jparisu/eProsima-CI/multiplatform/download_dependency@main
I left it as this so the last commit that updates all links changes also this one

2023-04-26 15:03 UTC, jparisu commented on .dev/multiplatform_support.md
> +```plantuml
We should arrive to a consensus about which method to use. I think plantuml is more extended.
If we decide to move to mermaid I'll change it

2023-04-28 07:43 UTC, JLBuenoLopez-eProsima commented on README.md
> +## Full Actions Implemented
I agree with your criteria of naming the folders with the version directly so they can be easily found.

2023-04-28 07:50 UTC, JLBuenoLopez-eProsima commented on .github/workflows/build_fastdds.yml
> +        uses: jparisu/eProsima-CI/multiplatform/generate_dependency@main
1. Cool, let us rename this specific action `generate_dependency` to `generate_dependency_artifact`.
2. The workflow that is generating the Fast DDS artifact can kept the current name `build_fastdds`.
3. The actions inside `multiplatform` are agnostic of the packages being built. Those packages are only defined on the workflows, so no name change is needed.
4. The `manual_build` workflow is really appreciated.

2023-04-28 07:51 UTC, JLBuenoLopez-eProsima commented on ubuntu/install_fast_dependencies/action.yml
> +    required: false
After discussing with Elbrus team, it is agreed that keeping the symmetry is preferable. So no modification is needed. Resolving conversation.

2023-04-28 07:54 UTC, JLBuenoLopez-eProsima commented on windows/colcon_build/action.yml
> +            -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} ${{ inputs.cmake_args_default }} ${{ inputs.cmake_args }}
I have seen the updated comment. Thanks! Resolving.

2023-04-28 08:01 UTC, JLBuenoLopez-eProsima commented on ubuntu/sphinx_docs/action.yml
> +        target_workspace: '${{ github.workspace }}/install'
We have agreed that we should merge as it is and that Elbrus repositories will try to work towards integration into the Annapurna's team infrastructure.

2023-04-28 08:26 UTC, JLBuenoLopez-eProsima commented on README.md
> +  uses: jparisu/eProsima-CI/multiplatform/download_dependency@main
Ok. But I was not referring to the repository itself but to the version of the action. I will leave it pending.

2023-04-28 08:28 UTC, JLBuenoLopez-eProsima commented on .dev/multiplatform_support.md
> +```plantuml
I am not against plantuml. What I am saying is that these documents are intended to be read in GitHub and GitHub is not formatting/interpreting the plantuml code, so we need to look for alternatives so the information you are trying to convey really is shown properly formatted.

2023-04-28 08:34 UTC, JLBuenoLopez-eProsima commented on README.md
> +  - *Only for documentation projects based in `cmake_utils`*.
:sweat_smile: sorry for being ambiguous myself. I was referring to the `cmake_utils` repository, and not to the Sphinx one.

2023-04-28 08:42 UTC, JLBuenoLopez-eProsima reviewed
I have left some conversations unresolved, but it is mostly done. There are some documentation improvements I would personally like to see:

* Add references in the README to the `.dev` documents (because they explain how to generate the artifacts, give contributing guidelines, etc).
* The README finishes with a cliffhanger. I suppose we should finish the section or just remove it and include it at a later time.
* I would like a section in README with a list of the external actions and maybe their licenses.

2023-04-28 08:42 UTC, JLBuenoLopez-eProsima commented on .dev/versioning_guidelines.md
> +Minor version should preserve old API, as actions names and locations and arguments anrevisionsd arguments names.
:see_no_evil:

2023-04-28 10:39 UTC, jparisu commented on README.md
> +These are the artifacts that are generated every night with the latest versions of each project:
:sweat:

2023-04-28 10:59 UTC, jparisu commented on README.md
> +  uses: jparisu/eProsima-CI/multiplatform/download_dependency@main
If I understand correctly, you suggest to write `jparisu/eProsima-CI/multiplatform/download_dependency@vX.Y`.
I suggest to leave it this way so every time a new version is going to be updated, you can find everywhere for `@main` and set it to `@vX.Y`, and this includes this, so it will change along the rest.

2023-05-03 10:44 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2023-05-03 10:53 UTC, jparisu commented
All actions references changed in commit https://github.com/eProsima/eProsima-CI/pull/17/commits/bd7451d2740262b69077e105f6049185782d233d

2023-05-03 11:06 UTC, JLBuenoLopez-eProsima requested changes

2023-05-03 11:06 UTC, JLBuenoLopez-eProsima commented on ubuntu/uncrustify/action.yml
> +<<<<<<<< HEAD:ubuntu-22.04/uncrustify/action.yml
I believe this should not be here :sweat:

Also, I think that in some rebase was moved from the proper folder. And also, not sure if it is the latest version.

2023-05-03 11:06 UTC, JLBuenoLopez-eProsima commented on ubuntu/sphinx_docs/action.yml
> +        workflow_source_repository: jparisu/eProsima-CI
Reference have not been changed here

2023-05-03 12:23 UTC, JLBuenoLopez-eProsima commented on ubuntu/uncrustify/action.yml
> ->>>>>>>> main:ubuntu/uncrustify/action.yml
I do not think the conflict is solved in this way: only the `install_uncrustify` action should be called.

Also, there `ament_lint` clone is from one fork maintained in your personal repository. Do we want to merge it or do we consider forking that repository in eProsima?

2023-05-03 12:58 UTC, rsanchez15 approved these changes

2023-05-03 13:01 UTC, merged