Update fastdds-build workflow to manually set dependencies version
eProsima/eProsima-CI pull request #35
Opened 2023-09-20 10:59 UTC by rsanchez15

2023-09-20 12:40 UTC, JLBuenoLopez-eProsima requested changes

2023-09-20 12:40 UTC, JLBuenoLopez-eProsima commented on .github/workflows/build_fastdds.yml
> -        default: main
Maybe we should consider keeping this argument in order to use different colcon.meta depending on the branch.

2023-09-20 12:40 UTC, JLBuenoLopez-eProsima commented on .github/workflows/build_fastdds.yml
> +          source_repository_branch: ${{ env.default_configuration_branch }}
If the environment variable is removed:

```suggestion
          source_repository_branch: main
```

2023-09-20 12:40 UTC, JLBuenoLopez-eProsima commented on .github/workflows/build_fastdds.yml
> +        uses: eProsima/eProsima-CI/multiplatform/fetch_fastdds_manual@feature/manual_fastdds_build
Before merging:

```suggestion
        uses: eProsima/eProsima-CI/multiplatform/fetch_fastdds_manual@main
```

2023-09-20 12:40 UTC, JLBuenoLopez-eProsima commented on multiplatform/fetch_fastdds_manual/action.yml
> +      uses: eProsima/eProsima-CI/ubuntu/fetch_fastdds_manual@feature/manual_fastdds_build
Before merging:

```suggestion
      uses: eProsima/eProsima-CI/ubuntu/fetch_fastdds_manual@main
```

Apply also to other occurrences in this PR.

2023-09-20 12:43 UTC, JLBuenoLopez-eProsima commented
It should be nice to update the README including this new action in order to keep the repo documented.

2023-09-20 12:47 UTC, rsanchez15 commented on windows/fetch_fastdds_manual/action.yml
> +        Write-Host '  - Fast CDR: $env:INPUTS_FASTDDS_BRANCH'
That's exactly what happenned. Updated!

2023-09-20 12:56 UTC, rsanchez15 commented on .github/workflows/build_fastdds.yml
>    default_configuration_branch: main
keeping the `built_configuration_branch` argument for colcon.meta file

2023-09-20 12:58 UTC, rsanchez15 commented on .github/workflows/build_fastdds.yml
> +          source_repository_branch: ${{ env.default_configuration_branch }}
Env variable not removed

2023-09-20 14:25 UTC, JLBuenoLopez-eProsima commented on ubuntu/fetch_fastdds_manual/action.yml
> +        echo "  - Fast CDR: ${{ inputs.fastdds_branch }}"
This suggestion has been overlooked. The windows action has the same typo.

2023-09-20 14:28 UTC, JLBuenoLopez-eProsima commented on windows/fetch_fastdds_manual/action.yml
> +        Write-Host '  - Fast CDR: $env:INPUTS_FASTDDS_BRANCH'
I am not completely sure that:

```
Write-Host '  - Foonathan Memory Vendor: ${{ inputs.foonathan_memory_vendor_branch }}'
```

works as you expect. Otherwise, instead of

```
Write-Host '  - Foonathan Memory Vendor: $env:INPUTS_FOONATHAN_MEMORY_VENDOR_BRANCH'
```

it would have been easier to use

```
Write-Host '  - Foonathan Memory Vendor: ${{ env.foonathan_memory_vendor_branch }}'
```

Have you checked the output?

2023-09-20 14:32 UTC, rsanchez15 commented on windows/fetch_fastdds_manual/action.yml
> +        Write-Host '  - Fast CDR: $env:INPUTS_FASTDDS_BRANCH'
Yes, you can check the output [here](https://github.com/eProsima/eProsima-CI/actions/runs/6249545085/job/16966435849)

2023-09-20 14:33 UTC, rsanchez15 commented on ubuntu/fetch_fastdds_manual/action.yml
> +        echo "  - Fast CDR: ${{ inputs.fastdds_branch }}"
Now it's done

2023-10-24 13:08 UTC, JLBuenoLopez-eProsima reviewed
A minor typo

2023-10-24 13:08 UTC, JLBuenoLopez-eProsima commented on README.md
> +> :page_facing_up: Fast DDS manual build allows to specify Fast DDS and its eProsima dependencies version as inputs of the workflow. In order to use the manually set versions instead the ones taken f
```suggestion
> :page_facing_up: Fast DDS manual build allows to specify Fast DDS and its eProsima dependencies version as inputs of the workflow. In order to use the manually set versions instead of the ones taken from the `.repos` file, just disable `use_repos_file` option.
```

Can the line be broken after the `.`?

2023-10-24 13:26 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2023-10-24 13:29 UTC, merged