Uncrustify action
eProsima/eProsima-CI pull request #4
Opened 2023-03-02 11:02 UTC by jparisu

2023-03-06 13:55 UTC, rsanchez15 requested changes

2023-03-06 13:55 UTC, rsanchez15 commented on README.md
> +> This is the eProsima Annapurna Team branch of eprosima-CI
```suggestion
```

2023-03-06 13:55 UTC, rsanchez15 commented on README.md
> +This is a github CI auxiliary repo that contains common github steps and actions shared along multiple eProsima libraries and tools.
I wouldn't differentiate between steps and actions as everything is an action. I'd also add a link to every action.yml file in each description so we can review the input arguments there.

2023-03-06 13:55 UTC, rsanchez15 commented on actions/python_linter/action.yml
> +  # This argument is passed to a grep function to make the filter, so use grep arguments
This should be part of the description

2023-03-06 13:55 UTC, rsanchez15 commented on actions/uncrustify/action.yml
> +  # This argument is passed to a grep function to make the filter, so use grep arguments
Same as before

2023-03-06 13:55 UTC, rsanchez15 commented on ubuntu/set_platform/action.yml
> +        echo "::group::Set ubuntu version in evn var ${{ inputs.ubuntu_version_env }}"
```suggestion
        echo "::group::Set ubuntu version in env var ${{ inputs.ubuntu_version_env }}"
```

2023-03-06 13:55 UTC, rsanchez15 commented on ubuntu/install_apt_packages/action.yml
> +  custom_packages:
I'd save this packages internally and use two inputs arguments, one for the user's packages and another to install or not default packages

2023-03-06 13:55 UTC, rsanchez15 commented on ubuntu/install_python_packages/action.yml
> +    default: 'vcstool setuptools'
Same comment as in "Install apt packages"

2023-03-06 13:55 UTC, rsanchez15 commented on actions/uncrustify/action.yml
> +          src
Do not break lines here

2023-03-06 13:55 UTC, rsanchez15 commented on actions/uncrustify/action.yml
> +          origin/${GITHUB_HEAD_REF}
Do you mean `${{ github.head_ref }}` and `${{ github.base_ref }}`?

2023-03-06 15:31 UTC, jparisu commented on ubuntu/install_apt_packages/action.yml
> +  custom_packages:
That is not the idea of this action. This is used every time is required to install something from apt, sometimes more than once in the same workflow.
I do not get why add a "yes/no default" argument when could have a default argument.

2023-03-06 15:32 UTC, jparisu commented on actions/uncrustify/action.yml
> +          origin/${GITHUB_HEAD_REF}
This is as it was in other repos, and it works. I have not tried the other way

2023-03-07 11:04 UTC, JLBuenoLopez-eProsima commented on actions/uncrustify/action.yml
> +      shell: bash
This step can be removed. There is an option to launch the workflow (and consequently the action) only when some specific files have been modified:

```
on:
  pull_request:
    # Only run uncrustify action when a source or header file has been modified.
    paths:
      - '**.cpp'
      - '**.hpp'
      - '.h'
      - '.cxx'
```

Therefore, I suggest documenting this precondition and assuming that the workflow takes charge of calling the action whenever a change has occurred and the difference in this case would never be empty.

2023-03-07 11:10 UTC, JLBuenoLopez-eProsima commented on actions/uncrustify/action.yml
> +    default: "-e '\\.h' -e '\\.hpp' -e '\\.cpp' -e '\\.ipp'"
I suggest adding .cxx as default extension too

2023-03-07 11:21 UTC, JLBuenoLopez-eProsima commented on ubuntu/install_python_packages/action.yml
> +    description: 'Wether to install the eProsima related python packages.'
```suggestion
    description: 'Whether to install the eProsima related python packages.'
```

2023-03-07 11:23 UTC, jparisu commented on actions/uncrustify/action.yml
> +      shell: bash
I would not mix workflow logic with action logic.
Assuming the workflow will do this has 2 inconveniences:

1. This action is no longer usable as action, just as workflow
2. This will force the user of the action to set those values in its workflow.

I will agree to make this in a way that if there are no files, it does not run the linter

2023-03-07 11:28 UTC, JLBuenoLopez-eProsima commented on actions/uncrustify/action.yml
> +      shell: bash
I was thinking about reducing the intermediate steps, but I agree with your arguments. And this step is not really that time-consuming to consider removing it from the action.

2023-03-07 11:57 UTC, jparisu commented on actions/uncrustify/action.yml
> +          origin/${GITHUB_HEAD_REF}
Also they are only availables when in a pull request

2023-03-08 07:19 UTC, rsanchez15 requested changes

2023-03-08 07:19 UTC, rsanchez15 commented on ubuntu/install_apt_packages/action.yml
> +    default: 1
I've never seen that "boolean types" are used like this in github actions as every input is treated as a string. Check how github@checkout implements them [here](https://github.com/actions/checkout/blob/main/action.yml#L62-L70).

2023-03-13 13:17 UTC, JesusPoderoso approved these changes
LGTM

2023-03-13 13:37 UTC, merged