Bring default fastdds and fastcdr versions back to master
eProsima/eProsima-CI pull request #46
Opened 2023-12-19 08:33 UTC by rsanchez15

2023-12-19 09:11 UTC, juanlofer-eprosima requested changes

2023-12-19 09:11 UTC, juanlofer-eprosima commented on ubuntu/install_fastdds_dependencies/action.yml
> +      uses: eProsima/eProsima-CI/ubuntu/setup_cmake@feature/fastdds-version
I believe it should be possible to specify the cmake version to be used in each OS. This way, we would be able to easily test different setups, and also allow each OS to compile with its default cmake version (instead of a fixed one for all of them).

2023-12-19 09:12 UTC, juanlofer-eprosima commented on ubuntu/install_fastdds_dependencies/action.yml
> +      uses: eProsima/eProsima-CI/ubuntu/setup_cmake@feature/fastdds-version
Remember to set actions path to main before merging.

2023-12-19 09:34 UTC, rsanchez15 commented on ubuntu/install_fastdds_dependencies/action.yml
> +      uses: eProsima/eProsima-CI/ubuntu/setup_cmake@feature/fastdds-version
But we already know that it won't compile for old versions of cmake so I'll keep it this way for now

2023-12-19 10:34 UTC, EduPonz requested changes

2023-12-19 10:34 UTC, EduPonz commented on ubuntu/setup_cmake/action.yml
We already have a multiplatform external action for this: https://github.com/eProsima/eProsima-CI/blob/main/external/get-cmake/action.yml

2023-12-19 12:10 UTC, rsanchez15 commented on ubuntu/setup_cmake/action.yml
Applied in 5d4c067

2023-12-20 06:02 UTC, EduPonz commented on ubuntu/setup_cmake/action.yml
> +      if: contains( ${{ env.EPROSIMA_UBUNTU_VERSION }} , '20.04' )
I'm wondering whether this logic can be moved to `install_fastdds_dependencies`. Are you planning on using `setup_cmake` elsewhere? If you aren't then I'd move the platform logic to `install_fastdds_dependencies` just to maintain one less action, but if you think it's valuable to have `setup_cmake` I'm OK with that

2023-12-20 06:25 UTC, rsanchez15 commented on ubuntu/setup_cmake/action.yml
> +      if: contains( ${{ env.EPROSIMA_UBUNTU_VERSION }} , '20.04' )
This is not planned to be used elsewhere but to be used in future versions of Ubuntu so it can be easily adapted to any old Ubuntu version that we may want to support. This way everything is encapsulated in just one action instead of having this kind of logic in `install_fastdds_dependencies` action.

2023-12-20 06:31 UTC, EduPonz approved these changes

2023-12-20 06:46 UTC, merged