[20529] Add skip_existing option to vcs_import action
eProsima/eProsima-CI pull request #63
Opened 2024-02-27 09:40 UTC by EduPonz

## Description

This PR adds a `skip_existing` boolean option to the `vcs_import` action.

## Contributor Checklist
- [x] Commit messages follow the company guidelines. 
- [x] Changes are API compatible. 
- [x] New features have been added to the `versions.md` and `README.md` files (if applicable).

## Reviewer Checklist
- [ ] The title and description correctly express the PR's purpose.
- [ ] The Contributor checklist is correctly filled.

2024-02-27 09:52 UTC, JesusPoderoso approved these changes
LGTM

2024-02-27 10:54 UTC, JesusPoderoso requested changes
NIT according [this](https://github.com/eProsima/Fast-DDS/actions/runs/8062697354/job/22022975664?pr=4456)

2024-02-27 10:54 UTC, JesusPoderoso commented on ubuntu/vcs_import/action.yml
> +          SKIP_EXISTING="--skip_existing"
```suggestion
          SKIP_EXISTING="--skip-existing"
```

2024-02-27 10:54 UTC, JesusPoderoso commented on windows/vcs_import/action.yml
> +          $SKIP_EXISTING = "--skip_existing"
```suggestion
          $SKIP_EXISTING = "--skip-existing"
```

2024-02-27 10:58 UTC, JesusPoderoso approved these changes
LGTM

2024-02-28 06:05 UTC, EduPonz commented
Merging this, it was tested successfully [here](https://github.com/eProsima/Fast-DDS/actions/runs/8062697354/job/22039143601?pr=4456#step:8:64)

2024-02-28 06:05 UTC, merged